### ISSUE TITLE
cant install "aibolit" using different python versions

### ISSUE THREAD

**Issue by sv-atoslav** [cqfn/aibolit#666]
OS AND Python versions ([pyenv](https://github.com/pyenv/pyenv) used):
```
$ lsb_release -a
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
$ python3 --version
Python 3.10.4
$ pyenv versions
* system (set by /home/sviatoslav/.pyenv/version)
  3.7.7
```
## Steps to reproduce:
before repeating, create folder `aibolit3.10` and `aibolit3.7` in downloads (or other locations)
### Try 1 with python3.10 (latest)
* `$ python3 --version`  
`Python 3.10.4`
* `cd ~/Downloads/aibolit3.10`
* create [virtual enviroment](https://docs.python.org/3/installing/index.html?highlight=virtualenv)
```
$ virtualenv venv
created virtual environment CPython3.10.4.final.0-64 in 203ms
  creator CPython3Posix(dest=/home/sviatoslav/Downloads/aibolit3.10/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/sviatoslav/.local/share/virtualenv)
    added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
$ source venv/bin/activate
```
* installation
```
$ pip install aibolit
Collecting aibolit
  Using cached aibolit-1.2.5-py2.py3-none-any.whl (12.3 MB)
  Downloading aibolit-1.2.4-py2.py3-none-any.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 3.2 MB/s eta 0:00:00
  Downloading aibolit-1.2.3-py2.py3-none-any.whl (12.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 4.0 MB/s eta 0:00:00
  Downloading aibolit-1.1.3-py2.py3-none-any.whl (12.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 3.1 MB/s eta 0:00:00
Collecting networkx==2.4
  Using cached networkx-2.4-py3-none-any.whl (1.6 MB)
Collecting aibolit
  Downloading aibolit-1.1.2-py2.py3-none-any.whl (12.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 3.6 MB/s eta 0:00:00
  Downloading aibolit-1.1.1-py2.py3-none-any.whl (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 4.2 MB/s eta 0:00:00
  Downloading aibolit-1.1.0-py2.py3-none-any.whl (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 2.9 MB/s eta 0:00:00
  Downloading aibolit-1.0.4-py2.py3-none-any.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 3.0 MB/s eta 0:00:00
  Downloading aibolit-1.0.3-py2.py3-none-any.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 3.3 MB/s eta 0:00:00
  Downloading aibolit-1.0.2-py2.py3-none-any.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 3.6 MB/s eta 0:00:00
  Downloading aibolit-1.0.1-py2.py3-none-any.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 2.2 MB/s eta 0:00:00
  Downloading aibolit-1.0.0-py2.py3-none-any.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 2.8 MB/s eta 0:00:00
  Downloading aibolit-0.0.6-py2.py3-none-any.whl (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 2.4 MB/s eta 0:00:00
Collecting flake8==3.7.9
  Using cached flake8-3.7.9-py2.py3-none-any.whl (69 kB)
Collecting scipy==1.4.1
  Using cached scipy-1.4.1.tar.gz (24.6 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3833 lines of output]
      Ignoring numpy: markers 'python_version == "3.5" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.5" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting setuptools
        Using cached setuptools-62.3.2-py3-none-any.whl (1.2 MB)
      Collecting Cython>=0.29.13
        Using cached Cython-0.29.30-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
      Collecting numpy==1.17.3
        Using cached numpy-1.17.3.zip (6.4 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting pybind11>=2.4.0
        Using cached pybind11-2.9.2-py2.py3-none-any.whl (213 kB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (setup.py): started
        Building wheel for numpy (setup.py): still running...
        Building wheel for numpy (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [3096 lines of output]
            Running from numpy source directory.
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/home/sviatoslav/Downloads/aibolit3.10/venv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            blis_info:
            customize UnixCCompiler
              libraries blis not found in ['/home/sviatoslav/Downloads/aibolit3.10/venv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            openblas_info:
            customize UnixCCompiler
            customize UnixCCompiler
              libraries openblas not found in ['/home/sviatoslav/Downloads/aibolit3.10/venv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_3_10_blas_threads_info:
            Setting PTATLAS=ATLAS
            customize UnixCCompiler
              libraries tatlas not found in ['/home/sviatoslav/Downloads/aibolit3.10/venv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_3_10_blas_info:
            customize UnixCCompiler
              libraries satlas not found in ['/home/sviatoslav/Downloads/aibolit3.10/venv/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
 
             [...long error log...]

            /usr/include/python3.10/pyhash.h:10:23: note: declared here
               10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
                  |                       ^~~~~~~~~~~~~~
            numpy/core/src/multiarray/scalartypes.c.src: In function ‘clongdouble_arrtype_hash’:
            numpy/core/src/multiarray/scalartypes.c.src:3319:31: error: incompatible type for argument 1 of ‘_Py_HashDouble’
             3319 |     hashreal = _Py_HashDouble((double)
                  |                               ^~~~~~~~
                  |                               |
                  |                               double
             3320 |             (((PyC@name@ScalarObject *)obj)->obval).real);
                  |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            In file included from /usr/include/python3.10/Python.h:77,
                             from numpy/core/src/multiarray/scalartypes.c.src:3:
            /usr/include/python3.10/pyhash.h:10:38: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘double’
               10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
                  |                                      ^~~~~~~~~~
            numpy/core/src/multiarray/scalartypes.c.src:3319:16: error: too few arguments to function ‘_Py_HashDouble’
             3319 |     hashreal = _Py_HashDouble((double)
                  |                ^~~~~~~~~~~~~~
            In file included from /usr/include/python3.10/Python.h:77,
                             from numpy/core/src/multiarray/scalartypes.c.src:3:
            /usr/include/python3.10/pyhash.h:10:23: note: declared here
               10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
                  |                       ^~~~~~~~~~~~~~
            numpy/core/src/multiarray/scalartypes.c.src:3325:31: error: incompatible type for argument 1 of ‘_Py_HashDouble’
             3325 |     hashimag = _Py_HashDouble((double)
                  |                               ^~~~~~~~
                  |                               |
                  |                               double
             3326 |             (((PyC@name@ScalarObject *)obj)->obval).imag);
                  |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            In file included from /usr/include/python3.10/Python.h:77,
                             from numpy/core/src/multiarray/scalartypes.c.src:3:
            /usr/include/python3.10/pyhash.h:10:38: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘double’
               10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
                  |                                      ^~~~~~~~~~
            numpy/core/src/multiarray/scalartypes.c.src:3325:16: error: too few arguments to function ‘_Py_HashDouble’
             3325 |     hashimag = _Py_HashDouble((double)
                  |                ^~~~~~~~~~~~~~
            In file included from /usr/include/python3.10/Python.h:77,
                             from numpy/core/src/multiarray/scalartypes.c.src:3:
            /usr/include/python3.10/pyhash.h:10:23: note: declared here
               10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
                  |                       ^~~~~~~~~~~~~~
            numpy/core/src/multiarray/scalartypes.c.src: In function ‘half_arrtype_hash’:
            numpy/core/src/multiarray/scalartypes.c.src:3341:27: error: incompatible type for argument 1 of ‘_Py_HashDouble’
             3341 |     return _Py_HashDouble(npy_half_to_double(((PyHalfScalarObject *)obj)->obval));
                  |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  |                           |
                  |                           double
            In file included from /usr/include/python3.10/Python.h:77,
                             from numpy/core/src/multiarray/scalartypes.c.src:3:
            /usr/include/python3.10/pyhash.h:10:38: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘double’
               10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
                  |                                      ^~~~~~~~~~
            numpy/core/src/multiarray/scalartypes.c.src:3341:12: error: too few arguments to function ‘_Py_HashDouble’
             3341 |     return _Py_HashDouble(npy_half_to_double(((PyHalfScalarObject *)obj)->obval));
                  |            ^~~~~~~~~~~~~~
            In file included from /usr/include/python3.10/Python.h:77,
                             from numpy/core/src/multiarray/scalartypes.c.src:3:
            /usr/include/python3.10/pyhash.h:10:23: note: declared here
               10 | PyAPI_FUNC(Py_hash_t) _Py_HashDouble(PyObject *, double);
                  |                       ^~~~~~~~~~~~~~
            numpy/core/src/multiarray/scalartypes.c.src: In function ‘longdouble_arrtype_hash’:
            numpy/core/src/multiarray/scalartypes.c.src:3312:1: warning: control reaches end of non-void function [-Wreturn-type]
             3312 | }
                  | ^
            numpy/core/src/multiarray/scalartypes.c.src: In function ‘float_arrtype_hash’:
            numpy/core/src/multiarray/scalartypes.c.src:3312:1: warning: control reaches end of non-void function [-Wreturn-type]
             3312 | }
                  | ^
            numpy/core/src/multiarray/scalartypes.c.src: In function ‘half_arrtype_hash’:
            numpy/core/src/multiarray/scalartypes.c.src:3342:1: warning: control reaches end of non-void function [-Wreturn-type]
             3342 | }
                  | ^
            error: Command "x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild/src.linux-x86_64-3.1/numpy/core/src/umath -Ibuild/src.linux-x86_64-3.1/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.1/numpy/core/src/common -Inumpy/core/include -Ibuild/src.linux-x86_64-3.1/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/sviatoslav/Downloads/aibolit3.10/venv/include -I/usr/include/python3.10 -Ibuild/src.linux-x86_64-3.1/numpy/core/src/common -Ibuild/src.linux-x86_64-3.1/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.1/numpy/core/src/common -Ibuild/src.linux-x86_64-3.1/numpy/core/src/npymath -c build/src.linux-x86_64-3.1/numpy/core/src/multiarray/scalartypes.c -o build/temp.linux-x86_64-cpython-310/build/src.linux-x86_64-3.1/numpy/core/src/multiarray/scalartypes.o -MMD -MF build/temp.linux-x86_64-cpython-310/build/src.linux-x86_64-3.1/numpy/core/src/multiarray/scalartypes.o.d" failed with exit status 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> numpy
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      WARNING: You are using pip version 22.0.4; however, version 22.1.1 is available.
      You should consider upgrading via the '/home/sviatoslav/Downloads/aibolit3.10/venv/bin/python -m pip install --upgrade pip' command.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
### Try 2 with python3.7 (by [readme](https://github.com/cqfn/aibolit#how-to-use-))
* change venv
```
$ deactivate
$ cd ../aibolit3.7
$ pyenv local 3.7.7
$ virtualenv --python /home/sviatoslav/.pyenv/shims/python3.7 venv
created virtual environment CPython3.7.7.final.0-64 in 183ms
  creator CPython3Posix(dest=/home/sviatoslav/Downloads/aibolit3.7/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/sviatoslav/.local/share/virtualenv)
    added seed packages: pip==22.0.2, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
$ source venv/bin/activate
$ python3 --version
Python 3.7.7
```
* installation
```
$ pip install aibolit
Collecting aibolit
  Using cached aibolit-1.2.5-py2.py3-none-any.whl (12.3 MB)
Collecting deprecated==1.2.10
  Using cached Deprecated-1.2.10-py2.py3-none-any.whl (8.7 kB)
Collecting tqdm==4.32.1
  Using cached tqdm-4.32.1-py2.py3-none-any.whl (49 kB)
[... using cached other dependencies ...]
Collecting certifi>=2017.4.17
  Using cached certifi-2022.5.18.1-py3-none-any.whl (155 kB)
Collecting tenacity>=6.2.0
  Using cached tenacity-8.0.1-py3-none-any.whl (24 kB)
Installing collected packages: typed-ast, snowballstemmer, pytz, mypy-extensions, mccabe, cchardet, cached-property, alabaster, wrapt, urllib3, typing-extensions, tqdm, tenacity, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, soupsieve, six, pyparsing, Pygments, pyflakes, pycodestyle, numpy, MarkupSafe, lxml, joblib, imagesize, idna, graphviz, entrypoints, docutils, decorator, cycler, coverage, charset-normalizer, certifi, babel, scipy, requests, python-dateutil, plotly, packaging, networkx, mypy, kiwisolver, Jinja2, javalang, flake8, deprecated, beautifulsoup4, sphinx, scikit-learn, pandas, matplotlib, codecov, catboost, aibolit
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1 Pygments-2.12.0 aibolit-1.2.5 alabaster-0.7.12 babel-2.10.1 beautifulsoup4-4.8.2 cached-property-1.2.0 catboost-0.22 cchardet-2.1.6 certifi-2022.5.18.1 charset-normalizer-2.0.12 codecov-2.0.15 coverage-5.0.3 cycler-0.11.0 decorator-5.1.1 deprecated-1.2.10 docutils-0.18.1 entrypoints-0.3 flake8-3.7.9 graphviz-0.20 idna-3.3 imagesize-1.3.0 javalang-0.13.0 joblib-1.1.0 kiwisolver-1.4.2 lxml-4.5.0 matplotlib-3.2.1 mccabe-0.6.1 mypy-0.770 mypy-extensions-0.4.3 networkx-2.4 numpy-1.18.1 packaging-21.3 pandas-1.0.0 plotly-5.8.0 pycodestyle-2.5.0 pyflakes-2.1.1 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.1 requests-2.27.1 scikit-learn-0.22.1 scipy-1.4.1 six-1.16.0 snowballstemmer-2.2.0 soupsieve-2.3.2.post1 sphinx-2.3.1 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-2.0.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.5 tenacity-8.0.1 tqdm-4.32.1 typed-ast-1.4.3 typing-extensions-4.2.0 urllib3-1.26.9 wrapt-1.14.1
```
* try launch
```
$ aibolit --help
Traceback (most recent call last):
  File "/home/sviatoslav/Downloads/aibolit3.7/venv/bin/aibolit", line 5, in <module>
    from aibolit.__main__ import main
  File "/home/sviatoslav/Downloads/aibolit3.7/venv/lib/python3.7/site-packages/aibolit/__main__.py", line 43, in <module>
    import numpy as np  # type: ignore
  File "/home/sviatoslav/Downloads/aibolit3.7/venv/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/sviatoslav/Downloads/aibolit3.7/venv/lib/python3.7/site-packages/numpy/core/__init__.py", line 106, in <module>
    from . import _dtype_ctypes
  File "/home/sviatoslav/Downloads/aibolit3.7/venv/lib/python3.7/site-packages/numpy/core/_dtype_ctypes.py", line 25, in <module>
    import _ctypes
ModuleNotFoundError: No module named '_ctypes'
$ pip install _ctypes
ERROR: Invalid requirement: '_ctypes'
```
Please, fix it.

**Comment by lyriccoder** [comment]
Hi, @sv-atoslav 
1)  Aibolit is only supported for Python 3.7.7 as it is declared in `Readme.md`
2) It's a problem with your `pyenv` environment, not with `aibolit`.

Try to do the following:

```
sudo apt-get install libffi-dev
pyenv uninstall 3.7.7
pyenv install 3.7.7
```
